import { createI18n } from "vue-i18n";

const messages = {
    en: {
        home: "Home",
        dashboard: "Dashboard",
        userRoles: "User Roles",
        addUserRole: "Add User Role",
        userRoleList: "User Role List",
        description: "Description",
        actions: "Actions",
        classRoomsList: "Class Rooms List",
        classRooms: "Class Rooms",
        addClassRoom: "Add Class Room",
        organization: "Organization",
        name: "Name",
        email: "Email",
        telephone: "Telephone",
        teachers: "Teachers",
        registeredAt: "Registered At",
        back: "Back",
        basicInformation: "Basic Information",
        teachersInformation: "Teachers Information",
        classRoomName: "Class Room Name",
        submit: "Submit",
        pleaseWait: "Please wait",
        editClassRoom: "Edit Class Room",
        parentsList: "Parents List",
        parents: "Parents",
        addParent: "Add Parent",
        userRole: "User Role",
        address: "Address",
        searchParents: "Search Parents",
        firstName: "First Name",
        lastName: "Last Name",
        phoneNumber: "Phone Number",
        username: "Username",
        password: "Password",
        confirmPassword: "Confirm Password",
        studentsList: "Students List",
        addStudent: "Add Student",
        students: "Students",
        searchStudents: "Search students",
        dateOfBirth: "Date of birth",
        age: "Age",
        classRoom: "Class Room",
        guardian: "Guardian",
        gender: "Gender",
        specialNotice: "Special Notice",
        additionalInformation: "Additional Information",
        chooseGender: "Choose gender",
        chooseOrganization: "Choose organization",
        chooseClassRoom: "Choose classroom",
        chooseGuardian: "Choose Guardian",
        reset: "Reset",
        title: "Title",
        featureImage: "Feature Image",
        gallery: "Gallery",
        galleryList: "Gallery List",
        addGallery: "Add Gallery",
        contentImages: "Content Images",
        newsFeed: "News Feed",
        latestClassRoomActivity: "Latest ClassRoom Activity",
        classRoomActivities: "ClassRoom Activities",
        previousPosts: "Previous Posts",
        readMore: "Read More",
        attendance: "Attendance",
        attendanceList: "Attendance List",
        searchAttendace: "Search Attendance",
        chooseStudents: "Choose Students",
        updatePassword: "Update Password",
        login: "Login",
        loginSubTitle: "If you have an account, please login",
        enterUserame: "Enter Username",
        enterPassword: "Enter Password",
        logIn: "Log In",
        changeLanguage: "Change language",
        english: "English",
        german: "German",
        goodJob: "Good job",
        successfulyLoggedIn: "You have successfully logged in",
        okGotIt: "Ok, got it",
        opps: "Oops",
        theEnteredPasswordIsIncorrect: "The Entered Password is incorrect",
        tryAgain: "Try again",
        users: "Users",
        organizations: "Organizations",
        chat: "Chat",
        settings: "Settings"
    },
    de: {
        home: "Home",
        dashboard: "Dashboard",
        userRoles: "Benutzerrollen",
        addUserRole: "Benuterrolle hinzufügen",
        userRoleList: "Benutzerrollen Liste",
        description: "Beschreibung",
        actions: "Aktionen",
        classRoomsList: "Gruppen-Liste",
        classRooms: "Klassenzimmer",
        addClassRoom: "Gruppe hinzufügen",
        organization: "Kindergarten",
        name: "Name",
        email: "E-Mail",
        telephone: "Telefonnummer",
        teachers: "Kindergärtner/-in",
        registeredAt: "Registriert bei",
        back: "Zurück",
        basicInformation: "Allgemeine Informationen",
        teachersInformation: "Allgemeine Informationen",
        classRoomName: "Gruppen-Name",
        submit: "Bestätigen",
        pleaseWait: "Bitte warten",
        editClassRoom: "Gruppe bearbeiten",
        parentsList: "Eltern Übersicht",
        parents: "Eltern",
        addParent: "Elternteil hinzufügen",
        userRole: "Benutzerrolle",
        address: "Addresse",
        searchParents: "Eltern suchen",
        firstName: "Vorname",
        lastName: "Nachname",
        phoneNumber: "Telefonnummer",
        username: "Benutzername",
        password: "Passwort",
        confirmPassword: "Passwort bestätigen",
        studentsList: "Kinder Übersicht",
        addStudent: "Kinder hinzufügen",
        students: "Kinder",
        searchStudents: "Kind suchen",
        dateOfBirth: "Geburtsdatum",
        age: "Alter",
        classRoom: "Gruppe",
        guardian: "Eltern",
        gender: "Geschlecht",
        specialNotice: "Notiz",
        additionalInformation: "Zusatzinformationen",
        chooseGender: "Geschlecht wählen",
        chooseOrganization: "Organisation wählen",
        chooseClassRoom: "Gruppe wählen",
        chooseGuardian: "Eltern wählen",
        reset: "Zurücksetzen",
        title: "Titel",
        featureImage: "Vorschaubild",
        gallery: "Gallerie",
        galleryList: "Gallerie Übersicht",
        addGallery: "Gallerie hinzufügen",
        contentImages: "Bilder",
        newsFeed: "Neuigkeiten",
        latestClassRoomActivity: "Aktuellste Neuigkeiten",
        classRoomActivities: "Aktivitäten der Gruppe",
        previousPosts: "Letzet Post",
        readMore: "Mehr anzeigen",
        attendance: "Teilnahme",
        attendanceList: "Anwesenheitsliste",
        searchAttendace: "Anwesenheit durchsuchen",
        chooseStudents: "Kinder wählen",
        updatePassword: "Kennwort aktualisieren",
        login: "Anmeldung",
        loginSubTitle: "Falls Sie einen Account haben, melden sie sich bitte an",
        enterUserame: "Benutzernamen eingeben",
        enterPassword: "Passwort eingeben",
        logIn: "Anmelden",
        changeLanguage: "Sprache wechseln",
        english: "Englisch",
        german: "Deutsch",
        goodJob: "Gute Arbeit",
        successfulyLoggedIn: "Sie haben sich erfolgreich angemeldet",
        okGotIt: "OK, verstanden",
        opps: "Oops",
        theEnteredPasswordIsIncorrect: "Das eingegebene Passwort ist Inkorrekt",
        tryAgain: "Erneut versuchen",
        users: "Benutzer",
        organizations: "Organisierungen",
        chat: "Chat",
        settings: "Einstellungen"
    },
};

const i18n = createI18n({
    legacy: false,
    locale: "fr",
    globalInjection: true,
    messages,
});
  
export default i18n;