import { createI18n } from "vue-i18n";

const messages = {
    en: {
        home: "Home",
        dashboard: "Dashboard",
        userRoles: "User Roles",
        addUserRole: "Add User Role",
        userRoleList: "User Role List",
        description: "Description",
        actions: "Actions",
        classRoomsList: "Class Rooms List",
        classRooms: "Class Rooms",
        addClassRoom: "Add Class Room",
        organization: "Organization",
        name: "Name",
        email: "Email",
        telephone: "Telephone",
        teachers: "Teachers",
        registeredAt: "Registered At",
        back: "Back",
        basicInformation: "Basic Information",
        teachersInformation: "Teachers Information",
        classRoomName: "Class Room Name",
        submit: "Submit",
        pleaseWait: "Please wait",
        editClassRoom: "Edit Class Room",
        parentsList: "Parents List",
        parents: "Parents",
        addParent: "Add Parent",
        userRole: "User Role",
        address: "Address",
        searchParents: "Search Parents",
        firstName: "First Name",
        lastName: "Last Name",
        phoneNumber: "Phone Number",
        username: "Username",
        password: "Password",
        confirmPassword: "Confirm Password",
        studentsList: "Students List",
        addStudent: "Add Student",
        students: "Students",
        searchStudents: "Search students",
        dateOfBirth: "Date of birth",
        age: "Age",
        classRoom: "Class Room",
        guardian: "Guardian",
        gender: "Gender",
        specialNotice: "Special Notice"
    },
    de: {
        home: "Heim",
        dashboard: "Armaturenbrett",
        userRoles: "Benutzerregeln",
        addUserRole: "Benutzerrolle hinzufügen",
        userRoleList: "Liste der Benutzerrollen",
        description: "Beschreibung",
        actions: "Aktionen",
        classRoomsList: "Liste der Klassenräume",
        classRooms: "Klassenräume",
        addClassRoom: "Klassenzimmer hinzufügen",
        organization: "Organisation",
        name: "Name",
        email: "Email",
        telephone: "Telefon",
        teachers: "Lehrer",
        registeredAt: "Registriert bei",
        back: "Zurück",
        basicInformation: "Grundinformation",
        teachersInformation: "Informationen für Lehrer",
        classRoomName: "Name des Klassenzimmers",
        submit: "Einreichen",
        pleaseWait: "Bitte warten",
        editClassRoom: "Klassenzimmer bearbeiten",
        parentsList: "Lijst van ouders",
        parents: "Ouders",
        addParent: "Ouder toevoegen",
        userRole: "Gebruikersrol",
        address: "Adres",
        searchParents: "Zoek ouders",
        firstName: "Voornaam",
        lastName: "Achternaam",
        phoneNumber: "Telefoonnummer",
        username: "Gebruikersnaam",
        password: "Wachtwoord",
        confirmPassword: "bevestig wachtwoord",
        studentsList: "Studentenlijst",
        addStudent: "Leerling toevoegen",
        students: "Studenten",
        searchStudents: "Zoek studenten",
        dateOfBirth: "Geboortedatum",
        age: "Leeftijd",
        classRoom: "Klaslokaal",
        guardian: "Voogd",
        gender: "Geslacht",
        specialNotice: "Speciale mededeling"
    },
};

const i18n = createI18n({
    legacy: false,
    locale: "fr",
    globalInjection: true,
    messages,
});
  
export default i18n;